apiVersion: v1
kind: Service
metadata:
  name: {{ include "kiri.fullname" . }}
  labels:
    {{- include "kiri.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4566
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kiri.selectorLabels" . | nindent 4 }}
